import { ImageSourcePropType } from "react-native";

export const CHARACTERS: Record<string, ImageSourcePropType> = {
  "p01": require("../assets/images/guess_who/characters/p01.png"),
  "p02": require("../assets/images/guess_who/characters/p02.png"),
  "p03": require("../assets/images/guess_who/characters/p03.png"),
  "p04": require("../assets/images/guess_who/characters/p04.png"),
  "p05": require("../assets/images/guess_who/characters/p05.png"),
  "p06": require("../assets/images/guess_who/characters/p06.png"),
  "p07": require("../assets/images/guess_who/characters/p07.png"),
  "p08": require("../assets/images/guess_who/characters/p08.png"),
  "p09": require("../assets/images/guess_who/characters/p09.png"),
  "p10": require("../assets/images/guess_who/characters/p10.png"),
  "p11": require("../assets/images/guess_who/characters/p11.png"),
  "p12": require("../assets/images/guess_who/characters/p12.png"),
  "p13": require("../assets/images/guess_who/characters/p13.png"),
  "p14": require("../assets/images/guess_who/characters/p14.png"),
  "p15": require("../assets/images/guess_who/characters/p15.png"),
  "p16": require("../assets/images/guess_who/characters/p16.png"),
  "p17": require("../assets/images/guess_who/characters/p17.png"),
  "p18": require("../assets/images/guess_who/characters/p18.png"),
  "p19": require("../assets/images/guess_who/characters/p19.png"),
  "p20": require("../assets/images/guess_who/characters/p20.png"),
  "p21": require("../assets/images/guess_who/characters/p21.png"),
  "p22": require("../assets/images/guess_who/characters/p22.png"),
  "p23": require("../assets/images/guess_who/characters/p23.png"),
  "p24": require("../assets/images/guess_who/characters/p24.png"),
  "p25": require("../assets/images/guess_who/characters/p25.png"),
  "p26": require("../assets/images/guess_who/characters/p26.png"),
  "p27": require("../assets/images/guess_who/characters/p27.png"),
  "p28": require("../assets/images/guess_who/characters/p28.png"),
  "p29": require("../assets/images/guess_who/characters/p29.png"),
  "p30": require("../assets/images/guess_who/characters/p30.png"),
  "p31": require("../assets/images/guess_who/characters/p31.png"),
  "p32": require("../assets/images/guess_who/characters/p32.png"),
};
