name: tcc_project

networks:
  tcc_net:
    name: tcc_net

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:17.5
    container_name: tcc_postgres
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tcc_net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tcc_backend
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    networks:
      - tcc_net
    command: ["node", "dist/main.js"]

  coturn:
    image: instrumentisto/coturn
    container_name: tcc_coturn
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "50000-50001:50000-50001/udp"
    environment:
      - TURN_PORT=3478
      - LISTENING_IP=0.0.0.0
      - EXTERNAL_IP=${EXTERNAL_IP}
      - REALM=${TURN_REALM}
      - USER=${TURN_USER}:${TURN_PASS}
    command:
      - --lt-cred-mech
      - --fingerprint
      - --no-cli
      - --no-tls
      - --no-dtls
      - --realm=${TURN_REALM}
      - --user=${TURN_USER}:${TURN_PASS}
      - --min-port=50000
      - --max-port=50001
    networks:
      - tcc_net

  nginx:
    image: nginx:latest
    container_name: tcc_nginx
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - tcc_net
