import { GuessWhoCharacter } from "../entities/guess-who-character.entity";

export const GUESS_WHO_CHARACTERS: GuessWhoCharacter[] = [
    { id: 1, name: 'Maya', image: 'p01' },
    { id: 2, name: 'Ethan', image: 'p02' },
    { id: 3, name: 'Liam', image: 'p03' },
    { id: 4, name: 'Noah', image: 'p04' },
    { id: 5, name: 'Clara', image: 'p05' },
    { id: 6, name: 'Jack', image: 'p06' },
    { id: 7, name: 'Aisha', image: 'p07' },
    { id: 8, name: 'Walter', image: 'p08' },
    { id: 9, name: 'Chloe', image: 'p09' },
    { id: 10, name: 'Ben', image: 'p10' },
    { id: 11, name: 'Olivia', image: 'p11' },
    { id: 12, name: 'Daniel', image: 'p12' },
    { id: 13, name: 'Jessica', image: 'p13' },
    { id: 14, name: 'Jayden', image: 'p14' },
    { id: 15, name: 'Jordan', image: 'p15' },
    { id: 16, name: 'Mildred', image: 'p16' },
    { id: 17, name: 'Ryan', image: 'p17' },
    { id: 18, name: 'Tom', image: 'p18' },
    { id: 19, name: 'Arthur', image: 'p19' },
    { id: 20, name: 'Miguel', image: 'p20' },
    { id: 21, name: 'Andrew', image: 'p21' },
    { id: 22, name: 'Leo', image: 'p22' },
    { id: 23, name: 'Stella', image: 'p23' },
    { id: 24, name: 'Scott', image: 'p24' },
    { id: 25, name: 'Isabella', image: 'p25' },
    { id: 26, name: 'Julian', image: 'p26' },
    { id: 27, name: 'Charles', image: 'p27' },
    { id: 28, name: 'Evelyn', image: 'p28' },
    { id: 29, name: 'Freddie', image: 'p29' },
    { id: 30, name: 'Darius', image: 'p30' },
    { id: 31, name: 'Marcus', image: 'p31' },
    { id: 32, name: 'Elliott', image: 'p32' },
];
